@echo ; This file generated by make_module_def.cmd > module.def
@echo LIBRARY "msvcp140_app" >> module.def
@echo EXPORTS >> module.def
@echo // This file generated by make_module_def.cmd > msvcp140.cpp


dumpbin /exports  "C:\Windows\System32\msvcp140.dll" | for /f "tokens=4 delims= " %%i in ('findstr /R /C:"         .... .. ........ .*"') do @echo     %%i=msvcp140.%%i >> module.def && @echo void %%i(){} >> msvcp140.cpp