@echo ; This file generated by make_module_def.cmd > module.def
@echo LIBRARY "vcruntime140_app" >> module.def
@echo EXPORTS >> module.def

@echo // This file generated by make_module_def.cmd > forwards.cpp

dumpbin /exports  "c:\Program Files\WindowsApps\Microsoft.VCLibs.140.00_14.0.26706.0_x86__8wekyb3d8bbwe\vcruntime140_app.dll" | for /f "tokens=4 delims= " %%i in ('findstr /R /C:"         .... .. ........ .*"') do @echo     %%i=vcruntime140_app.%%i >> module.def && @echo void %%i(){} >> forwards.cpp
