@echo ; This file generated by make_module_def.cmd > module.def
@echo LIBRARY "vcruntime140_app" >> module.def
@echo EXPORTS >> module.def
@echo // This file generated by make_module_def.cmd > vcruntime140.cpp


dumpbin /exports  "C:\Windows\System32\vcruntime140.dll" | for /f "tokens=4 delims= " %%i in ('findstr /R /C:"         .... .. ........ .*"') do @echo     %%i=vcruntime140.%%i >> module.def && @echo void %%i(){} >> vcruntime140.cpp
